/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgentRouteImport } from './routes/agent'
import { Route as BrandRouteImport } from './routes/brand'
import { Route as MerchRouteImport } from './routes/merch'
import { Route as PlansRouteImport } from './routes/plans'
import { Route as ProductRouteImport } from './routes/product'
import { Route as StablecoinsRouteImport } from './routes/stablecoins'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentRoute = AgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandRoute = BrandRouteImport.update({
  id: '/brand',
  path: '/brand',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchRoute = MerchRouteImport.update({
  id: '/merch',
  path: '/merch',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansRoute = PlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductRoute = ProductRouteImport.update({
  id: '/product',
  path: '/product',
  getParentRoute: () => rootRouteImport,
} as any)
const StablecoinsRoute = StablecoinsRouteImport.update({
  id: '/stablecoins',
  path: '/stablecoins',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agent': typeof AgentRoute
  '/brand': typeof BrandRoute
  '/merch': typeof MerchRoute
  '/plans': typeof PlansRoute
  '/product': typeof ProductRoute
  '/stablecoins': typeof StablecoinsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agent': typeof AgentRoute
  '/brand': typeof BrandRoute
  '/merch': typeof MerchRoute
  '/plans': typeof PlansRoute
  '/product': typeof ProductRoute
  '/stablecoins': typeof StablecoinsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agent': typeof AgentRoute
  '/brand': typeof BrandRoute
  '/merch': typeof MerchRoute
  '/plans': typeof PlansRoute
  '/product': typeof ProductRoute
  '/stablecoins': typeof StablecoinsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agent'
    | '/brand'
    | '/merch'
    | '/plans'
    | '/product'
    | '/stablecoins'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agent'
    | '/brand'
    | '/merch'
    | '/plans'
    | '/product'
    | '/stablecoins'
  id:
    | '__root__'
    | '/'
    | '/agent'
    | '/brand'
    | '/merch'
    | '/plans'
    | '/product'
    | '/stablecoins'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentRoute: typeof AgentRoute
  BrandRoute: typeof BrandRoute
  MerchRoute: typeof MerchRoute
  PlansRoute: typeof PlansRoute
  ProductRoute: typeof ProductRoute
  StablecoinsRoute: typeof StablecoinsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent': {
      id: '/agent'
      path: '/agent'
      fullPath: '/agent'
      preLoaderRoute: typeof AgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand': {
      id: '/brand'
      path: '/brand'
      fullPath: '/brand'
      preLoaderRoute: typeof BrandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merch': {
      id: '/merch'
      path: '/merch'
      fullPath: '/merch'
      preLoaderRoute: typeof MerchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans': {
      id: '/plans'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof PlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product': {
      id: '/product'
      path: '/product'
      fullPath: '/product'
      preLoaderRoute: typeof ProductRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stablecoins': {
      id: '/stablecoins'
      path: '/stablecoins'
      fullPath: '/stablecoins'
      preLoaderRoute: typeof StablecoinsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentRoute: AgentRoute,
  BrandRoute: BrandRoute,
  MerchRoute: MerchRoute,
  PlansRoute: PlansRoute,
  ProductRoute: ProductRoute,
  StablecoinsRoute: StablecoinsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
